### ISSUE TITLE
Testing with pyactor

### ISSUE THREAD

**Issue by christianzanger** [pedrotgn/pyactor#2]
While working with unittests and pyactor, I've run into a problem when I want to execute more than one test. The example project of pyactor only works with one test, so there's no reference on how to do it with multiple tests. If testing for more than one test, and using the function set_context() in the setUp() function (as in the example), a Bad Core Type exception is thrown. 

Sample code:
```python
import unittest
from gotorrent import tracker
from pyactor.context import set_context, create_host, sleep, shutdown


class TestTracker(unittest.TestCase):

    def setUp(self):
        #Gets executed before every test
        set_context()
        self.h = create_host()
        self.t = self.h.spawn("tracker", tracker.Tracker)

    def tearDown(self):
        # Gets executed after every test
        shutdown()
    def test_empty_swarm(self):
        self.t.init_start()
        self.assertEqual(self.t.get_peers("tetris"), {})

    def test_peers(self):
        self.t.init_start()
        self.t.announce("tetris", "christian")
        self.assertEqual(self.t.get_peers("tetris").keys(), ["christian"])
        sleep(12)
        self.assertEqual(self.t.get_peers("tetris"), {})


if __name__ == '__main__':
    print "Run the tests"
    suite = unittest.TestLoader().loadTestsFromTestCase(TestStringMethods)
    unittest.TextTestRunner(verbosity=2).run(suite)
```

For now, I've found a simple yet not diserable solution:

```python
   try:
       set_context()
    except:
       pass
```

I think that the exception gets thrown because nose maybe uses multithreading for multiple tests, and since the contest is already set when executing another thread a Bad Core Type Exception gets thrown, as there already is a context and shutdown() wasn't called yet. Any ideas?

**Comment by danielBCN** [comment]
Solved with the last commit.
Now `shutdown()` correctly cleans the core type.
