### ISSUE TITLE
proxy.py applies len() to a function

### ISSUE THREAD

**Issue by oscarbc96** [pedrotgn/pyactor#3]
When you call an ask method of a proxy, the following exception is raised:

`Traceback (most recent call last):
  File "/gotorrent/test/peer_test.py", line 38, in test_peer
    self.assertEqual(set(['peer1', 'peer2', 'peer3']), set(tracker.get_peers("file", True)))
  File "/usr/local/lib/python2.7/site-packages/pyactor-1.2.0-py2.7.egg/pyactor/proxy.py", line 145, in __call__
    raise result
TypeError: object of type 'function' has no len()
`

**Comment by danielBCN** [comment]
That was a problem with your code.
Hope you already solved it :-)
Clossing this now.
